{{- if .Values.cronjobs.enabled }}
{{- range .Values.cronjobs.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name | quote }}
  labels:
    app_name: {{ .Values.nameOverride }}
    app_env: {{ .Values.environment }}
    app: {{ .Values.nameOverride }}
spec:
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{- toYaml .podAnnotations | nindent 12 }}
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: {{ .restartPolicy }}
          containers:
            - name: {{ .name | quote }}
              image: "{{ .image.repository }}:{{ .image.tag }}"
              imagePullPolicy: {{ .image.pullPolicy }}
              command: {{ toYaml .command | nindent 16 }}
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              {{- if .env }}
              {{- range $key, $value := .env }}
                - name: {{ $key | quote }}
                  value: {{ $value | quote }}
              {{- end }}
              {{- end }}
              {{- if eq .envFrom "externalSecret" }}
              envFrom:
                - secretRef:
                    name: {{ printf "%s-%s" .Values.nameOverride .Values.externalSecret.suffix | quote }}
              {{- end }}
              volumeMounts:
                {{- toYaml .volumeMounts | nindent 16 }}
          volumes:
            {{- range .volumes }}
            - name: {{ .name | quote }}
              {{- if .configMap }}
              configMap:
                name: {{ .configMap.name | quote }}
              {{- end }}
            {{- end }}
{{- end }}
{{- end }}
